-- Blog System Database Setup
-- Run this in your Supabase SQL Editor

-- 1. Create the blogs table
create table if not exists blogs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Core Content
  title text not null,
  slug text not null unique,
  excerpt text not null, -- Short description for cards/SEO
  content text not null, -- Rich text / HTML
  featured_image text, -- URL to image
  
  -- SEO Fields
  meta_title text, -- If empty, falls back to title
  meta_description text, -- If empty, falls back to excerpt
  keywords text[], -- Array of SEO keywords
  
  -- Metadata
  author text default 'SDB LABEL Team',
  category text default 'Industry Insights',
  tags text[],
  
  -- Status
  is_published boolean default false,
  published_at timestamp with time zone
);

-- 2. Create indexes for performance
create index if not exists blogs_slug_idx on blogs (slug);
create index if not exists blogs_published_idx on blogs (is_published, published_at);

-- 3. Enable RLS (Row Level Security)
alter table blogs enable row level security;

-- 4. Create Policies

-- Policy: Anyone can view PUBLISHED blogs
create policy "Public can view published blogs"
  on blogs for select
  using ( is_published = true );

-- Policy: Authenticated users (Admins) can do EVERYTHING
-- Note: Since we are using a custom auth implementation in the specific Admin Code,
-- we might need to rely on the 'anon' key with RLS disabled strictly for the admin client 
-- OR strictly use the service_role key for admin actions if we want full security.
-- However, based on the previous setup, we are using the standard client. 
-- For simplicity in this specific "Admin Dashboard" context which seems to protect routes via code,
-- we will allow anon to read/write but we rely on the Application logic to secure the Admin usage.
-- Ideally, we should use Supabase Auth. 
-- For now, to match the existing 'consultancy_requests' patterns which disabled RLS:

-- TEMPORARY: Disable RLS to match existing project pattern (as seen in database-setup.sql)
-- "ALTER TABLE quotation_requests DISABLE ROW LEVEL SECURITY;"
alter table blogs disable row level security;

-- Grant permissions
grant all on blogs to anon;
grant all on blogs to authenticated;
grant usage on sequence blogs_id_seq to anon;
grant usage on sequence blogs_id_seq to authenticated;

-- 5. Auto-update 'updated_at' column
create or replace function update_modified_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language 'plpgsql';

create trigger update_blogs_modtime
    before update on blogs
    for each row
    execute procedure update_modified_column();
